// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings,
  updateSettings,
  updateComboStrategies,
  isCloudEnabled,
  getCloudUrl,
  getProviderConnectionsUnscoped,
  getProviderConnectionByIdUnscoped,
  createProviderConnectionUnscoped,
  updateProviderConnectionUnscoped,
  deleteProviderConnectionUnscoped,
  deleteProviderConnectionsByProviderUnscoped,
  reorderProviderConnectionsUnscoped,
  cleanupProviderConnectionsUnscoped,
  getProviderNodesUnscoped,
  getProviderNodeByIdUnscoped,
  createProviderNodeUnscoped,
  updateProviderNodeUnscoped,
  deleteProviderNodeUnscoped,
  getProxyPools,
  getProxyPoolById,
  createProxyPool,
  updateProxyPool,
  deleteProxyPool,
  getApiKeys,
  getApiKeyById,
  createApiKey,
  updateApiKey,
  deleteApiKey,
  validateApiKey,
  getApiKeyUsage,
  // YAN-364: new *Unscoped names; legacy names alias to the Unscoped twins.
  getCombosUnscoped,
  getCombosUnscoped as getCombos,
  getComboByIdUnscoped,
  getComboByIdUnscoped as getComboById,
  getComboByNameUnscoped,
  getComboByNameUnscoped as getComboByName,
  createComboUnscoped,
  createComboUnscoped as createCombo,
  updateComboUnscoped,
  updateComboUnscoped as updateCombo,
  deleteComboUnscoped,
  deleteComboUnscoped as deleteCombo,
  getModelAliasesUnscoped,
  getModelAliasesUnscoped as getModelAliases,
  setModelAliasUnscoped,
  setModelAliasUnscoped as setModelAlias,
  deleteModelAliasUnscoped,
  deleteModelAliasUnscoped as deleteModelAlias,
  getCustomModelsUnscoped,
  getCustomModelsUnscoped as getCustomModels,
  addCustomModelUnscoped,
  addCustomModelUnscoped as addCustomModel,
  deleteCustomModelUnscoped,
  deleteCustomModelUnscoped as deleteCustomModel,
  getMitmAlias,
  setMitmAliasAll,
  getPricing,
  getPricingForModel,
  getUserPricing,
  invalidatePricingCache,
  updatePricing,
  resetPricing,
  resetAllPricing,
  exportDb,
  importDb,
} from "@/lib/db/index.js";
