// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
export {
  statsEmitter,
  trackPendingRequest,
  getLiveSnapshot,
  saveRequestUsage,
  getUsageHistory,
  getUsageStatsUnscoped,
  getChartData,
  getUsageSavings,
  getUsageTotals,
  getLastActivity,
  getHomeSummary,
  recordFallbackHop,
  appendRequestLog,
  getRecentLogsUnscoped,
  saveRequestDetail,
  getRequestDetails,
  getRequestDetailById,
} from "@/lib/db/index.js";
