#!/usr/bin/env node
/**
 * Brand guard (YAN-322): fails when a 9router literal is added, so the rebrand
 * can't regress and its progress is measurable.
 *
 * It counts matches of PATTERN (case-insensitive) per file over tracked files
 * (`git grep`, so ignored and untracked files never count), skipping binaries
 * and the allowlist below.
 *
 * Ratchet: scripts/brand-guard.baseline.json holds the per-file counts. The
 * check fails when a file's count goes up or a new file appears. Lower counts
 * pass; record them with `npm run lint:brand -- --update`, which refuses to run
 * while anything went up. Every rebrand PR lowers the baseline for the files it
 * touches; the final sweep (YAN-343) takes it to zero.
 *
 * Usage: node scripts/brand-guard.mjs [--update]
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const PATTERN = "9router|9-router|nine[_-]?router|9ROUTER";
const BASELINE_PATH = "scripts/brand-guard.baseline.json";

/** Paths where the old name is allowed for good. Each needs a reason. */
const ALLOWED_PATHS = [
  // The brand module is the one registry of legacy values (LEGACY, UPSTREAM_CLIENT_IDS).
  "src/shared/brand/**",
  // Upstream copyright, kept verbatim.
  "**/LICENSE",
  // Generated by package managers.
  "**/package-lock.json",
  "**/pnpm-lock.yaml",
  "**/yarn.lock",
  "**/bun.lock",
  "**/bun.lockb",
  // Release history; only the release process edits it.
  "**/CHANGELOG.md",
  // Historical planning docs.
  "docs/plans/**",
  "docs/prps/**",
  "docs/superpowers/**",
  "docs/internal-docs/**",
  // The upgrade guide has to name what is being upgraded from.
  "UPGRADING.md",
  "gitbook/content/**/upgrading*",
  // Legacy inputs that compatibility tests read.
  "tests/fixtures/legacy/**",
  // The guard itself.
  "scripts/brand-guard.mjs",
  BASELINE_PATH,
  "tests/unit/brand-guard.test.js",
];

/** Lines where the old name is allowed for good, wherever the file is. */
const ALLOWED_LINE_MARKERS = [
  // Legacy compatibility branches, removed in v2 (handbook §3.6).
  "legacy(9router)",
];

/** Lines allowed only in README files: the "based on 9Router by decolua" credit. */
const README_FILE = /(^|\/)README[^/]*\.md$/i;
const README_CREDIT_MARKER = "decolua";

const MATCH = new RegExp(PATTERN, "gi");

function git(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
}

function isAllowedLine(file, line) {
  if (ALLOWED_LINE_MARKERS.some((marker) => line.includes(marker))) return true;
  return README_FILE.test(file) && line.includes(README_CREDIT_MARKER);
}

function countOccurrences(root) {
  const pathspecs = ALLOWED_PATHS.map((p) => `:(glob,exclude)${p}`);
  let output;
  try {
    output = git(
      ["grep", "-z", "-n", "-I", "-i", "-E", "-e", PATTERN, "--", ".", ...pathspecs],
      root,
    );
  } catch (error) {
    if (error.status === 1) return {}; // git grep: no matches
    throw error;
  }
  const counts = {};
  for (const record of output.split("\n")) {
    if (!record) continue;
    // -z output: <file>\0<line number>\0<line>
    const [file, , ...rest] = record.split("\0");
    const line = rest.join("\0");
    if (isAllowedLine(file, line)) continue;
    const hits = line.match(MATCH)?.length ?? 0;
    if (hits) counts[file] = (counts[file] ?? 0) + hits;
  }
  return counts;
}

function compare(baseline, current) {
  const increases = [];
  const decreases = [];
  for (const file of Object.keys({ ...baseline, ...current }).sort()) {
    const before = baseline[file] ?? 0;
    const after = current[file] ?? 0;
    if (after > before) increases.push({ file, before, after });
    else if (after < before) decreases.push({ file, before, after });
  }
  return { increases, decreases };
}

const sum = (counts) => Object.values(counts).reduce((a, b) => a + b, 0);

function sorted(counts) {
  return Object.fromEntries(
    Object.keys(counts)
      .sort()
      .map((file) => [file, counts[file]]),
  );
}

function describeChange({ file, before, after }) {
  return before === 0 ? `  ${file}: new file with ${after}` : `  ${file}: ${before} → ${after}`;
}

function main(argv) {
  const unknown = argv.filter((arg) => arg !== "--update");
  if (unknown.length) {
    console.error(`brand-guard: unknown argument ${unknown[0]}; usage: brand-guard.mjs [--update]`);
    return 2;
  }
  const update = argv.includes("--update");
  const root = git(["rev-parse", "--show-toplevel"], process.cwd()).trim();
  const baselineFile = path.join(root, BASELINE_PATH);
  const current = countOccurrences(root);
  const total = sum(current);
  const files = Object.keys(current).length;

  const write = () => {
    fs.mkdirSync(path.dirname(baselineFile), { recursive: true });
    fs.writeFileSync(baselineFile, `${JSON.stringify(sorted(current), null, 2)}\n`);
  };

  if (!fs.existsSync(baselineFile)) {
    if (!update) {
      console.error(`brand-guard: ${BASELINE_PATH} is missing; create it with --update. FAIL`);
      return 1;
    }
    write();
    console.log(
      `brand-guard: created ${BASELINE_PATH} with ${total} occurrences in ${files} files.`,
    );
    return 0;
  }

  const baseline = JSON.parse(fs.readFileSync(baselineFile, "utf8"));
  const { increases, decreases } = compare(baseline, current);
  const summary = `brand-guard: ${total} occurrences in ${files} files remaining (baseline ${sum(baseline)}).`;

  if (increases.length) {
    console.error(`${summary} FAIL`);
    console.error("New 9router literals (use the brand module, src/shared/brand, instead):");
    for (const change of increases) console.error(describeChange(change));
    if (update) console.error("brand-guard: --update refuses to raise the baseline.");
    return 1;
  }

  if (update) {
    if (decreases.length) write();
    console.log(`${summary} OK`);
    console.log(
      decreases.length
        ? `brand-guard: lowered the baseline for ${decreases.length} files.`
        : "brand-guard: baseline already up to date.",
    );
    return 0;
  }

  console.log(`${summary} OK`);
  if (decreases.length) {
    console.log(
      `brand-guard: ${decreases.length} files dropped below the baseline; record it with \`npm run lint:brand -- --update\`:`,
    );
    for (const change of decreases) console.log(describeChange(change));
  }
  return 0;
}

process.exitCode = main(process.argv.slice(2));
