#!/usr/bin/env node
/**
 * Brand guard (YAN-322, strict since YAN-343): fails on any 9router literal
 * outside the allowlist, so the rebrand can't regress.
 *
 * It matches PATTERN (case-insensitive) over tracked files (`git grep`, so
 * ignored and untracked files never count), skipping binaries, the allowed
 * paths and allowed lines below. Any remaining hit fails the check with its
 * file and line. Legacy values belong in the brand module (src/shared/brand);
 * a line that must keep the old name for compatibility carries `legacy(9router)`.
 *
 * Usage: node scripts/brand-guard.mjs
 */
import { execFileSync } from "node:child_process";

const PATTERN = "9router|9-router|nine[_-]?router|9ROUTER";

/** Paths where the old name is allowed for good. Each needs a reason. */
const ALLOWED_PATHS = [
  // The brand module is the one registry of legacy values (LEGACY, UPSTREAM_CLIENT_IDS),
  // and its tests pin those values and the brand switch.
  "src/shared/brand/**",
  "tests/unit/brand.test.js",
  "tests/unit/brand-switch.test.js",
  // i18n keys are the English source text each brand renders, plus their
  // translations. The 9router keys go when v2 drops the 9router brand id; new
  // ones can only come from src/, which this guard covers.
  "public/i18n/literals/**",
  // The image's fallback title must equal DEFAULT_BRAND_ID (docker-brand.test.js).
  // YAN-345 flips the default and removes this entry.
  "Dockerfile",
  // Describes the brand switch's current default; only /ycc:release-model edits it,
  // and the v1.0.0 release rewrites that line. YAN-345 removes this entry.
  "RELEASING.md",
  // Upstream copyright, kept verbatim.
  "**/LICENSE",
  // Generated by package managers.
  "**/package-lock.json",
  "**/pnpm-lock.yaml",
  "**/yarn.lock",
  "**/bun.lock",
  "**/bun.lockb",
  // Release history; only the release process edits it.
  "**/CHANGELOG.md",
  // Historical planning docs.
  "docs/plans/**",
  "docs/prps/**",
  "docs/superpowers/**",
  "docs/internal-docs/**",
  // The upgrade guide has to name what is being upgraded from.
  "UPGRADING.md",
  "gitbook/content/**/upgrading*",
  // Legacy inputs that compatibility tests read.
  "tests/fixtures/legacy/**",
  // The guard itself.
  "scripts/brand-guard.mjs",
  "tests/unit/brand-guard.test.js",
];

/** Lines where the old name is allowed for good, wherever the file is. */
const ALLOWED_LINE_MARKERS = [
  // Legacy compatibility branches, removed in v2 (handbook §3.6).
  "legacy(9router)",
];

/** Lines allowed only in README files: the "based on 9Router by decolua" credit. */
const README_FILE = /(^|\/)README[^/]*\.md$/i;
const README_CREDIT_MARKER = "decolua";

const MATCH = new RegExp(PATTERN, "gi");

function git(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
}

function isAllowedLine(file, line) {
  if (ALLOWED_LINE_MARKERS.some((marker) => line.includes(marker))) return true;
  return README_FILE.test(file) && line.includes(README_CREDIT_MARKER);
}

/** Every non-allowlisted hit as { file, line, hits, text }. */
function findHits(root) {
  const pathspecs = ALLOWED_PATHS.map((p) => `:(glob,exclude)${p}`);
  let output;
  try {
    output = git(
      ["grep", "-z", "-n", "-I", "-i", "-E", "-e", PATTERN, "--", ".", ...pathspecs],
      root,
    );
  } catch (error) {
    if (error.status === 1) return []; // git grep: no matches
    throw error;
  }
  const found = [];
  for (const record of output.split("\n")) {
    if (!record) continue;
    // -z output: <file>\0<line number>\0<line>
    const [file, line, ...rest] = record.split("\0");
    const text = rest.join("\0");
    if (isAllowedLine(file, text)) continue;
    const hits = text.match(MATCH)?.length ?? 0;
    if (hits) found.push({ file, line: Number(line), hits, text: text.trim() });
  }
  return found;
}

function main(argv) {
  if (argv.length) {
    console.error(
      `brand-guard: unexpected argument ${argv[0]}; the guard is strict and takes no arguments (the baseline was removed in YAN-343)`,
    );
    return 2;
  }
  const root = git(["rev-parse", "--show-toplevel"], process.cwd()).trim();
  const found = findHits(root);
  if (!found.length) {
    console.log("brand-guard: 0 occurrences. OK");
    return 0;
  }
  const total = found.reduce((sum, hit) => sum + hit.hits, 0);
  const files = new Set(found.map((hit) => hit.file)).size;
  console.error(`brand-guard: ${total} occurrences in ${files} files. FAIL`);
  for (const { file, line, text } of found)
    console.error(`  ${file}:${line}: ${text.slice(0, 160)}`);
  console.error(
    "Use the brand module (src/shared/brand), or mark a line that must keep the old name with `legacy(9router)`.",
  );
  return 1;
}

process.exitCode = main(process.argv.slice(2));
