// Database Models - Export all from localDb
export {
  getProviderConnectionsUnscoped,
  getProviderConnectionByIdUnscoped,
  createProviderConnectionUnscoped,
  updateProviderConnectionUnscoped,
  deleteProviderConnectionUnscoped,
  getProviderNodesUnscoped,
  getProviderNodeByIdUnscoped,
  createProviderNodeUnscoped,
  updateProviderNodeUnscoped,
  deleteProviderNodeUnscoped,
  getProxyPools,
  getProxyPoolById,
  createProxyPool,
  updateProxyPool,
  deleteProxyPool,
  deleteProviderConnectionsByProviderUnscoped,
  // YAN-364: new *Unscoped names; legacy names alias to the Unscoped twins.
  getCombosUnscoped,
  getCombosUnscoped as getCombos,
  getComboByIdUnscoped,
  getComboByIdUnscoped as getComboById,
  getComboByNameUnscoped,
  getComboByNameUnscoped as getComboByName,
  createComboUnscoped,
  createComboUnscoped as createCombo,
  updateComboUnscoped,
  updateComboUnscoped as updateCombo,
  deleteComboUnscoped,
  deleteComboUnscoped as deleteCombo,
  getModelAliasesUnscoped,
  getModelAliasesUnscoped as getModelAliases,
  setModelAliasUnscoped,
  setModelAliasUnscoped as setModelAlias,
  deleteModelAliasUnscoped,
  deleteModelAliasUnscoped as deleteModelAlias,
  getCustomModelsUnscoped,
  getCustomModelsUnscoped as getCustomModels,
  addCustomModelUnscoped,
  addCustomModelUnscoped as addCustomModel,
  deleteCustomModelUnscoped,
  deleteCustomModelUnscoped as deleteCustomModel,
  getMitmAlias,
  setMitmAliasAll,
  getApiKeys,
  createApiKey,
  deleteApiKey,
  validateApiKey,
  isCloudEnabled,
} from "@/lib/localDb";
